//Project 1
/*
 * Name: pre.c
 * Author: Ruben Suarez
 * Class: Operating Systems (CS 4328)
 * Instructor: Dr. Xiao Chen
 */

 /*
 The first program "pre.c" should read in a list of U.S. states and their populations. You can google to find the population information 
or just enter some numbers. Whether the numbers are correct or not is not our focus here. To be simple, you
can use the two-letter state abbreviation to represent each state. We assume there are at most 10 states in
the list. Enter the inputs through the keyboard and display the outputs on the screen. The inputs end when
an EOF (generated by Ctrl-D) is encountered. The outputs of the program should display the states whose population
is above 10 million.
 */

#include <stdio.h>
#include <string.h>


int main() {

    int count = 0;
    int c;

    struct State_Pop{
        char st[2];
        int pop;
    };

    struct State_Pop sp_Array[10];

    do{
        char s[2] = "";
        int p = 0;
        c = scanf("%s %d", s, &p );
        if(s != "" && p >= 0){
            strcpy(sp_Array[count].st, s);
            sp_Array[count].pop = p;
            count ++;
        }
    }while (c  != EOF);

    //printf("\nStates with populations > 10 million: \n");
    for(int i = 0; i < count; i++){
        if(sp_Array[i].pop > 9){
            printf("%s \n",sp_Array[i].st);
        }
    }

    return 0;
}
